version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    volumes:
      - ./node:/usr/src/node
    entrypoint: sh -c "npm install --prefix /usr/src/node && npm start --prefix /usr/src/node"
    ports:
      - 3000:3000
    tty: true
    depends_on:
      database:
        condition: service_healthy

  database:
    build: 
      context: ./database
    container_name: database
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

networks:
  node-network:
    driver: bridge

volumes:
  mysql:
    driver: local
